# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-08 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_otheruser_poke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='otheruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='main.User'),
        ),
        migrations.DeleteModel(
            name='OtherUser',
        ),
    ]
